StudentManagementUI/StudentManagement/Models/ErrorViewModel.cs
using System;

namespace StudentManagement.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

StudentManagementUI/StudentManagement/Models/Student.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace StudentManagement.Models
{
    public class Student
    {
        public int mssv { get; set; }

        [Required(ErrorMessage = "This field cannot be empty!")]
        public string fullname { get; set; }

        [Required(ErrorMessage = "This field cannot be empty!")]
        public string classname { get; set; }

        public string sex { get; set; }

        [Required(ErrorMessage ="This field cannot be empty!")]
        [Range(0,4, ErrorMessage = "GPA must be between 0 and 4!")]
        public double gpa { get; set; }
        
        public string avatar { get; set; }

        public Student()
        {

        }

    }
}

StudentManagementUI/StudentManagement/Controllers/StudentController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using StudentManagement.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System.Net.Http.Headers;
using System.Text.Json;
using System.Text;
using Newtonsoft.Json;

namespace StudentManagement.Controllers
{
    public class StudentController : Controller
    {


        private readonly IHttpClientFactory _clientFactory;
        private int orderBy = 0;
        private string url = "http://ec2-52-87-54-46.compute-1.amazonaws.com:8080";

        public IEnumerable<Student> students { get; set; }

        public StudentController(IHttpClientFactory _clientFactory)
        {
            this._clientFactory = _clientFactory;
        }

        public async Task<IActionResult> Index(int orderBy = 0)
        {
            this.orderBy = orderBy;
            var request = new HttpRequestMessage(HttpMethod.Get,
                url + "/student/getAll");

            var client = _clientFactory.CreateClient();
            client.DefaultRequestHeaders.Accept.Add(
                new MediaTypeWithQualityHeaderValue("application/json"));


            students = new List<Student>();
            try
            {
                var response = await client.SendAsync(request);

                if (response.IsSuccessStatusCode)
                {
                    var responseStream = await response.Content.ReadAsStreamAsync();
                    students = await System.Text.Json.JsonSerializer.DeserializeAsync<IEnumerable<Student>>(responseStream);

                }
                else
                {
                    students = new List<Student>();

                }
            }
            catch (Exception e)
            {
                Console.WriteLine(e.Message);
            }

            return View(students);
        }

        [HttpPost, ActionName("AddNewStudent")]
        public async Task<ActionResult> AddNewStudent(Student st)
        {

            var request = url + "/student/add";

            var client = _clientFactory.CreateClient();
            client.DefaultRequestHeaders.Accept.Add(
                new MediaTypeWithQualityHeaderValue("application/json"));


            //Converting the object to a json string. NOTE: Make sure the object doesn't contain circular references.
            string json = JsonConvert.SerializeObject(st);

            //Needed to setup the body of the request
            StringContent data = new StringContent(json, Encoding.UTF8, "application/json");


            //  var response = await client.SendAsync(request);
            var response = await client.PostAsync(request, data);
            var itemStudent = new Student();
            if (response.IsSuccessStatusCode)
            {
                var responseStream = await response.Content.ReadAsStreamAsync();
                itemStudent = await System.Text.Json.JsonSerializer.DeserializeAsync<Student>(responseStream);
            }
            else
            {
                itemStudent = new Student();
            }


            // return View(itemStudent);

            return RedirectToAction("Index");
        }

        public IActionResult AddStudent()
        {
            return View();
        }

        public async Task<ActionResult> EditStudent(int id)
        {
            var request = new HttpRequestMessage(HttpMethod.Get,
             url + "/student/getById/" + id);

            var client = _clientFactory.CreateClient();
            client.DefaultRequestHeaders.Accept.Add(
                new MediaTypeWithQualityHeaderValue("application/json"));

            var response = await client.SendAsync(request);
            var itemStudent = new Student();
            if (response.IsSuccessStatusCode)
            {
                var responseStream = await response.Content.ReadAsStreamAsync();
                itemStudent = await System.Text.Json.JsonSerializer.DeserializeAsync<Student>(responseStream);
            }
            else
            {
                itemStudent = new Student();
            }


            return View(itemStudent);
        }

        public async Task<ActionResult> UpdateStudent(Student st)
        {
            var request = "http://ec2-54-152-106-201.compute-1.amazonaws.com:8080" + "/student/update";

            var client = _clientFactory.CreateClient();
            client.DefaultRequestHeaders.Accept.Add(
                new MediaTypeWithQualityHeaderValue("application/json"));


            //Converting the object to a json string. NOTE: Make sure the object doesn't contain circular references.
            string json = JsonConvert.SerializeObject(st);

            //Needed to setup the body of the request
            StringContent data = new StringContent(json, Encoding.UTF8, "application/json");


            //  var response = await client.SendAsync(request);
            var response = await client.PutAsync(request, data);
            var itemStudent = new Student();
            if (response.IsSuccessStatusCode)
            {
                var responseStream = await response.Content.ReadAsStreamAsync();
                itemStudent = await System.Text.Json.JsonSerializer.DeserializeAsync<Student>(responseStream);
            }
            else
            {
                itemStudent = new Student();
            }


            return RedirectToAction("Index");
        }
        public async Task<IActionResult> DeleteStudent(int id)
        {
            var request = new HttpRequestMessage(HttpMethod.Delete,
             "http://ec2-54-152-106-201.compute-1.amazonaws.com:8080" + "/student/delete/" + id);

            var client = _clientFactory.CreateClient();
            client.DefaultRequestHeaders.Accept.Add(
                new MediaTypeWithQualityHeaderValue("application/json"));

            var response = await client.SendAsync(request);

            if (response.IsSuccessStatusCode)
            {
                //todo
            }
            else
            {
                //todo
            }
            return RedirectToAction("Index");
        }


        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

StudentManagementUI/StudentManagement/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - StudentManagement</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Student" asp-action="Index">StudentManagement</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Student" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Student" asp-action="AddStudent">AddStudent</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

StudentManagementUI/StudentManagement/Views/Student/AddStudent.cshtml
@model StudentManagement.Models.Student

@{
    ViewData["Title"] = "AddStudent";
}

<!DOCTYPE html>

<html>

<head>
    <meta name="viewport" content="width=device-width" />
</head>

<body>

    <h4>Add Student</h4>
    <hr />
    <h1 class="text-center" style="margin:40px">Student Information</h1>
    <form asp-controller="Student" ;>

        <div class="form-group">
            <label asp-for="@Model.fullname">FullName</label>
            <input asp-for="@Model.fullname" type="text" class="form-control" id="fullname">
            <span asp-validation-for="@Model.fullname" class="text-danger" id="errfullname"></span>

        </div>

        <div class="form-group">
            <label asp-for="@Model.classname">Class</label>
            <input asp-for="@Model.classname" type="text" class="form-control" id="classz">
            <span asp-validation-for="@Model.classname" class="text-danger" id="errclassz"></span>
        </div>
        <div class="form-group">
            <label asp-for="@Model.sex">Gender</label><br />
            <select asp-for="@Model.sex" name="sex" id="sex" runat="server">
                <option value="Male">Male</option>
                <option value="Female">Female</option>
                <option value="Other">Other</option>
            </select>
        </div>
        <div class="form-group">
            <label asp-for="@Model.gpa">GPA</label>
            <input asp-for="@Model.gpa" type="number" class="form-control" id="gpa" />
            <span asp-validation-for="@Model.gpa" class="text-danger" id="errgpa"></span>
        </div>

        <div class="buttons">
            <div class="upload-button">
                <div class="label">Click me!</div>
                <input id="files" name="files" type="file" size="1" />
                <br />
                <span id="errfile" class="text-danger"></span>
            </div>
        </div>
        <br />

        <button type="reset" class="btn btn-light">Reset</button>
        @*asp-action="AddNewStudent onclick="uploadFiles('files')" <form id="form" name="form" action="/uploader"
            enctype="multipart/form-data" method="post"> </form>"*@
        <button type="button" runat="server" class="btn btn-primary" onclick="uploadFiles('files')">Confirm </button>
        <script>

            function validation(student, file) {
                var result1 = true, result2 = true, result3 = true, result4 = true;

                if (!student.fullname || student.fullname.trim().length < 1) {
                    $('#errfullname').text('This field cannot be empty')
                    result1 = false;
                }
                if (!student.classname || student.classname.trim().length < 1) {

                    $('#errclassz').text('This field cannot be empty')
                    result2 = false;
                }

                if (!student.gpa || student.gpa > 4 || student.gpa < 0) {
                    $('#errgpa').text('GPA must be between 0 and 4!')
                    console.log("GPA:", student.gpa)
                    result3 = false;
                }
                if (!file) {
                    $('#errfile').text('This field cannot be empty')
                    result4 = false;
                }
                return result1 && result2 && result3 && result4;

            }

            function uploadFiles(inputId) {

                var result = confirm("Do you want to continue?");

                if (!result) {
                    return;
                }

                var formData = new FormData();
                var input = document.getElementById(inputId);
                var fullname = $('#fullname').val()
                var classz = $('#classz').val()
                var gpa = $('#gpa').val()
                var sex = $('#sex').val()


                var files = input.files;
                var student = {
                    "fullname": fullname,
                    "classname": classz,
                    "sex": sex,
                    "gpa": parseFloat(gpa)
                }
                console.log("GPA", student.gpa)
                console.log("FILE:", files[0])

                var isValid = validation(student, files[0])
                if (!isValid) {
                    return;
                }



                formData.append('student', new Blob([JSON.stringify(student)], { type: "application/json" }));
                formData.append('file', files[0]);

                console.log("STUDENT", student)
                $.ajax({
                    type: "POST",

                    url: 'http://ec2-52-87-54-46.compute-1.amazonaws.com:8080/student/add',

                    data: formData,
                    dataType: "json",
                    processData: false,
                    contentType: false,

                    error: function (result) {
                        alert("error");
                        console.log(result);
                    },
                    success: function (result) {

                        console.log("Host:", window.location.host)
                        window.location.href = window.location.protocol + "//" + window.location.host + "/Student"

                    }
                });
            }


        </script>


    </form>


    <div>
        <a asp-action="Index">Back to List</a>
    </div>

    @section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    }
</body>

</html>

StudentManagementUI/StudentManagement/Views/Student/EditStudent.cshtml
@model StudentManagement.Models.Student

@{
    ViewData["Title"] = "EditStudent";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Edit Student</title>
</head>
<body>

    <h4>Student</h4>
    <hr />
    <h1 class="text-center" style="margin:40px">Student Information</h1>
    <form asp-controller="Student" asp-action="UpdateStudent" method="post" onsubmit="return confirm('Are you sure you want to save changes?')" ;>
        <div class="form-group">
            <label asp-for="@Model.mssv">StudentID</label>
            <input asp-for="@Model.mssv" type="text" readonly class="form-control">

        </div>
        <div class="form-group">
            <label asp-for="@Model.fullname">Full Name</label>
            <input asp-for="@Model.fullname" type="text" class="form-control" required />
        </div>

        <div class="form-group">
            <label asp-for="@Model.classname">Class</label>
            <input asp-for="@Model.classname" type="text" class="form-control" required />
        </div>
        <div class="form-group">
            <label asp-for="@Model.sex">Gender</label><br />
            <select asp-for="@Model.sex" name="sex" id="sex" runat="server">
                <option value="Male">Male</option>
                <option value="Female">Female</option>
                <option value="Other">Other</option>
            </select>
        </div>
        <div class="form-group">
            <label asp-for="@Model.gpa">GPA</label>
            <input asp-for="@Model.gpa" type="number" step="0.01" min="0" max="4" class="form-control" />
        </div>
        <button type="reset" class="btn btn-light">Reset</button>
        <button type="submit" runat="server" class="btn btn-primary">Save</button>
    </form>

    <div>
        <a asp-action="Index">Back to List</a>
    </div>

</body>
</html>

StudentManagementUI/StudentManagement/Views/Student/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}
@model IEnumerable<StudentManagement.Models.Student>


<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>StudentList</title>
</head>
<body>
    <p>
        <a asp-action="AddStudent">Add Student</a>
    </p>
    <p>
        <a asp-action="AddStudent">Update Student</a>
    </p>
    <table class="table">
        <thead>
            <tr>
                <th scope="col">Student ID</th>
                <th scope="col">Avatar</th>
                <th scope="col">Full Name</th>
                <th scope="col">Class</th>
                <th scope="col">Gender</th>
                <th scope="col">GPA</th>
                <th scope="col"></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
                    @foreach (var sv in Model)
                    {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => sv.mssv)
                </td>
                <td>
                    <img src="@sv.avatar"
                         class="rounded-circle"
                         height="40" width="40"
                         asp-append-version="true" />
                </td>
                <td>
                    @Html.DisplayFor(modelItem => sv.fullname)
                </td>

                <td>
                    @Html.DisplayFor(modelItem => sv.classname)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => sv.sex)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => sv.gpa)
                </td>
                <td>
                    <a asp-controller="Student" asp-action="EditStudent" asp-route-id="@sv.mssv" class="btn btn-danger">Edit</a>
                    <a asp-controller="Student" asp-action="DeleteStudent" asp-route-id="@sv.mssv" class="btn btn-danger" onclick="return confirm('Are you sure you want to delete this item?')" ;>Delete</a>
                </td>
            </tr>
                    }
                </tbody>
    </table>
</body>
</html>